### ISSUE TITLE
How to use it with matplotlib?

### ISSUE THREAD

**Issue by chaoshengt** [ThomasBury/scicomap#1]
Dear @ThomasBury ,howto use this package with matplotlib?could you show a demo? :)

**Comment by ThomasBury** [comment]
Hi @chaoshengt, thank you for your Interest. I just added a section "Use with matplotlib" in the Readme. Here is the example that I added and that you'll find in the readme. After correcting the camp, you can fetch is using the method `.get_mpl_color_map()` and use it for any matplotlib figure ^^

```python
import matplotlib.pyplot as plt
import matplotlib as mpl
import scicomap as sc
from scicomap.utils import _fn_with_roots

# load the color map
div_map = sc.ScicoDiverging(cmap='watermelon')

# correct the colormap
div_map.unif_sym_cmap(lift=15, 
                      bitonic=False, 
                      diffuse=True)

# get the fixed color map
fixed_cmap = div_map.get_mpl_color_map()
print(type(fixed_cmap))

# use it as you like
im = _fn_with_roots()
norm = mpl.colors.CenteredNorm()
divnorm = mpl.colors.TwoSlopeNorm(vmin=-1, vcenter=0, vmax=1.25)
fig = plt.figure(figsize=(3,3), facecolor="white")
ax = fig.add_subplot(1, 1, 1, facecolor="white")
pos = ax.imshow(im, cmap=fixed_cmap, aspect="auto", norm=divnorm)
fig.colorbar(pos, ax=ax);
```

**Comment by chaoshengt** [comment]
> Hi @chaoshengt, thank you for your Interest. I just added a section "Use with matplotlib" in the Readme. Here is the example that I added and that you'll find in the readme. After correcting the camp, you can fetch is using the method `.get_mpl_color_map()` and use it for any matplotlib figure ^^
> 
> ```python
> import matplotlib.pyplot as plt
> import matplotlib as mpl
> import scicomap as sc
> from scicomap.utils import _fn_with_roots
> 
> # load the color map
> div_map = sc.ScicoDiverging(cmap='watermelon')
> 
> # correct the colormap
> div_map.unif_sym_cmap(lift=15, 
>                       bitonic=False, 
>                       diffuse=True)
> 
> # get the fixed color map
> fixed_cmap = div_map.get_mpl_color_map()
> print(type(fixed_cmap))
> 
> # use it as you like
> im = _fn_with_roots()
> norm = mpl.colors.CenteredNorm()
> divnorm = mpl.colors.TwoSlopeNorm(vmin=-1, vcenter=0, vmax=1.25)
> fig = plt.figure(figsize=(3,3), facecolor="white")
> ax = fig.add_subplot(1, 1, 1, facecolor="white")
> pos = ax.imshow(im, cmap=fixed_cmap, aspect="auto", norm=divnorm)
> fig.colorbar(pos, ax=ax);
> ```

So nice! Thank you @ThomasBury ! I will try and introduce to my friends. :)
